"""SQL page generation with syntax highlighting."""

from pathlib import Path
from typing import Optional

from .logger import get_logger

logger = get_logger(__name__)


def escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def generate_sql_page(
    sql_content: str,
    query_path: str,
    project_name: str,
    output_path: Path
) -> None:
    """Generate a standalone HTML page for SQL with syntax highlighting.
    
    Args:
        sql_content: The SQL query content
        query_path: Relative path to the SQL file (e.g., 'queries/foo.sql')
        project_name: Name of the project
        output_path: Absolute path where the HTML should be written
    """
    escaped_sql = escape_html(sql_content)
    query_name = Path(query_path).name
    
    html_content = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{escape_html(project_name)} - {escape_html(query_name)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    :root {{
      --primary: #1a365d;
      --primary-light: #2c5282;
      --accent: #3182ce;
      --font-sans: "Inter", "IBM Plex Sans", "Segoe UI", system-ui, -apple-system, sans-serif;
      --gray-50: #f7fafc;
      --gray-100: #edf2f7;
      --gray-200: #e2e8f0;
      --gray-600: #4a5568;
      --gray-800: #1a202c;
      --shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
      --code-bg: #0f172a;
      --code-text: #e2e8f0;
      --kw: #7dd3fc;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ 
      font-family: var(--font-sans);
      background: #ffffff; color: var(--gray-800);
      min-height: 100vh; display: flex; flex-direction: column;
    }}
    header {{ 
      padding: 0 32px; height: 64px; background: var(--primary);
      border-bottom: 1px solid #0f2744; display: flex;
      align-items: center; justify-content: space-between;
      box-shadow: var(--shadow); position: sticky; top: 0; z-index: 1000;
    }}
    .brand {{ 
      font-weight: 600; font-size: 18px; color: white;
      text-decoration: none; display: flex; align-items: center; gap: 12px;
    }}
    .brand-icon {{
      width: 32px; height: 32px; background: var(--accent);
      border-radius: 6px; display: flex; align-items: center;
      justify-content: center; font-weight: 700; font-size: 16px;
    }}
    .breadcrumb {{
      color: rgba(255, 255, 255, 0.7); font-size: 14px;
      display: flex; align-items: center; gap: 8px;
    }}
    .breadcrumb span {{
      color: white; font-weight: 500;
    }}
    main {{ 
      flex: 1; padding: 32px; max-width: 1200px; width: 100%; margin: 0 auto;
    }}
    h1 {{ 
      font-size: 20px; font-weight: 600; margin-bottom: 24px;
      color: var(--gray-800);
    }}
    pre {{ 
      margin: 0; white-space: pre; overflow: auto;
      background: var(--code-bg); border: 1px solid var(--gray-200);
      border-radius: 8px; padding: 20px;
      box-shadow: var(--shadow);
    }}
    code {{
      font-family: 'SF Mono', Monaco, 'Cascadia Code', 'Courier New', monospace;
      font-size: 14px; line-height: 1.6; color: var(--code-text);
    }}
    .kw {{ color: var(--kw); font-weight: 600; }}
    .back-link {{
      display: inline-block; margin-top: 24px;
      color: var(--accent); text-decoration: none;
      font-size: 14px; font-weight: 500;
    }}
    .back-link:hover {{ text-decoration: underline; }}
    footer {{
      color: var(--gray-600); font-size: 12px; padding: 24px 32px;
      text-align: center; border-top: 1px solid var(--gray-200);
    }}
  </style>
</head>
<body>
  <header>
    <div class="brand">
      <div class="brand-icon">D</div>
      <span>Digdag Workflow Graph</span>
    </div>
    <div class="breadcrumb">
      <span>{escape_html(project_name)}</span> / {escape_html(query_path)}
    </div>
  </header>
  <main>
    <h1>{escape_html(query_name)}</h1>
    <pre><code class="language-sql">{escaped_sql}</code></pre>
    <a href="javascript:history.back()" class="back-link">← Back to workflow</a>
  </main>
  <footer>Generated by digdag-graph</footer>
  <script>
    (function() {{
      const code = document.querySelector('pre code');
      if (!code) return;
      const text = code.textContent || '';
      const escaped = text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
      const keywords = /(\\bselect\\b|\\bfrom\\b|\\bwhere\\b|\\bjoin\\b|\\bon\\b|\\bgroup\\b|\\bby\\b|\\border\\b|\\blimit\\b|\\bcreate\\b|\\btable\\b|\\binsert\\b|\\binto\\b|\\bupdate\\b|\\bdelete\\b|\\bwith\\b|\\bunion\\b|\\bhaving\\b|\\bcase\\b|\\bwhen\\b|\\bthen\\b|\\belse\\b|\\bend\\b)/gi;
      const highlighted = escaped.replace(keywords, '<span class="kw">$1</span>');
      code.innerHTML = highlighted;
    }})();
  </script>
</body>
</html>"""
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write the HTML file
    output_path.write_text(html_content, encoding='utf-8')
    logger.debug(f"Generated SQL page: {output_path}")


def read_and_generate_sql_page(
    sql_file_path: Path,
    query_path: str,
    project_name: str,
    output_dir: Path
) -> Optional[str]:
    """Read SQL file and generate HTML page.
    
    Args:
        sql_file_path: Absolute path to the SQL file
        query_path: Relative path (e.g., 'queries/foo.sql')
        project_name: Project name
        output_dir: Base output directory for the project
    
    Returns:
        SQL content if successful, None otherwise
    """
    try:
        sql_content = sql_file_path.read_text(encoding='utf-8')
    except FileNotFoundError:
        logger.warning(f"SQL file not found: {sql_file_path}")
        sql_content = f"-- File not found: {sql_file_path}"
    except Exception as e:
        logger.error(f"Error reading SQL file {sql_file_path}: {e}")
        sql_content = f"-- Error reading file: {e}"
    
    # Generate output path preserving directory structure
    output_path = output_dir / Path(query_path).with_suffix('.html')
    
    generate_sql_page(sql_content, query_path, project_name, output_path)
    
    # Return relative path to the generated HTML file
    return str(Path(query_path).with_suffix('.html'))
